Remove the unused iterator
[2/55] Building CXX object Source/displayinfo/CMakeFiles/ClientDisplayInfo.dir/DisplayInfo.cpp.o
FAILED: Source/displayinfo/CMakeFiles/ClientDisplayInfo.dir/DisplayInfo.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DClientDisplayInfo_EXPORTS -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -I/Users/runner/work/ThunderClientLibraries/ThunderClientLibraries/ThunderClientLibraries/Source/displayinfo -I/Users/runner/work/ThunderClientLibraries/ThunderClientLibraries/ThunderClientLibraries/Source/displayinfo/include -isystem /Users/runner/work/ThunderClientLibraries/ThunderClientLibraries/Release/install/usr/include/Thunder -isystem /Users/runner/work/ThunderClientLibraries/ThunderClientLibraries/Release/install/usr/include -isystem /Users/runner/work/ThunderClientLibraries/ThunderClientLibraries/Release/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -O3 -DNDEBUG -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT Source/displayinfo/CMakeFiles/ClientDisplayInfo.dir/DisplayInfo.cpp.o -MF Source/displayinfo/CMakeFiles/ClientDisplayInfo.dir/DisplayInfo.cpp.o.d -o Source/displayinfo/CMakeFiles/ClientDisplayInfo.dir/DisplayInfo.cpp.o -c /Users/runner/work/ThunderClientLibraries/ThunderClientLibraries/ThunderClientLibraries/Source/displayinfo/DisplayInfo.cpp
/Users/runner/work/ThunderClientLibraries/ThunderClientLibraries/ThunderClientLibraries/Source/displayinfo/DisplayInfo.cpp:217:51: error: unused variable 'index' [-Werror,-Wunused-variable]
        OperationalStateChangeCallbacks::iterator index(_operationalStateCallbacks.find(callback));
                                                  ^
1 error generated.